tasks:
  - init: npm install
    command: npm run dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - ms-vscode.vscode-typescript-next
    - oderwat.indent-rainbow
    - wix.vscode-import-cost
    - kamikillerto.vscode-colorize
    - aaron-bond.better-comments
